# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/import
# Target is a library:  

include(../components_config.pri)

INSTALLS += target
target.path = $$PREFIX/lib/

HEADERS += tuppaletteimporter.h
SOURCES += tuppaletteimporter.cpp

*:!macx{
    CONFIG += dll warn_on
}

TEMPLATE = lib 
TARGET = tupimport

FRAMEWORK_DIR = $$TUPI_HOME/src/framework
include($$FRAMEWORK_DIR/framework.pri)
