# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

system( echo "TUPI_HOME = $$PWD     >  tupi.pri")
system( echo "BINDIR    = $$OUT_PWD >> tupi.pri")

CONFIG += ordered warn_on debug
TEMPLATE = subdirs 
SUBDIRS += src
# RESOURCES += src/resource.qrc
