# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/tools/filltool
# Target is a library:  

include(../tools_config.pri)

INSTALLS += target 
target.path = $$PREFIX/plugins/ 

HEADERS += filltool.h 
SOURCES += filltool.cpp

CONFIG += plugin warn_on
TEMPLATE = lib
TARGET = tupifilltool

FRAMEWORK_DIR = $$TUPI_HOME/src/framework
include($$FRAMEWORK_DIR/framework.pri)
