# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/pen
# Target is a library:  

include(../components_config.pri)

INSTALLS += target
target.path = $$PREFIX/lib/

HEADERS += tuppenwidget.h 

SOURCES += tuppenwidget.cpp 

*:!macx{
    CONFIG += dll warn_on
}

TEMPLATE = lib
TARGET = tupipen

FRAMEWORK_DIR = $$TUPI_HOME/src/framework
include($$FRAMEWORK_DIR/framework.pri)
