# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/export
# Target is a library:  

include(../components_config.pri)

INSTALLS += target
target.path = $$PREFIX/lib/

HEADERS += tupexportwidget.h 
SOURCES += tupexportwidget.cpp

*:!macx{
    CONFIG += dll warn_on
}

TEMPLATE = lib
TARGET = tupiexport

FRAMEWORK_DIR = $$TUPI_HOME/src/framework
include($$FRAMEWORK_DIR/framework.pri)
