# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins
# Target is a subdirs project 

!include(../../config.pri) {
    error("Please configure first")
}

INCLUDEPATH += $$TUPI_HOME/src/libbase
SUBDIRS += tools
CONFIG += ordered warn_on 
TEMPLATE = subdirs 
